[package]
name = "acts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
swc_common = "0.31.18"
swc_ecma_ast = "0.107.2"
swc_ecma_parser = { version = "0.137.4", features = ["typescript"] }

[lib]
name = "act_lib"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[profile.release]
lto = true
strip = true
opt-level = 3
