[package]
name = "actually_checked_typescript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
swc_common = "0.29.27"
swc_ecma_ast = "0.96.0"
swc_ecma_parser = "0.124.0"
