[package]
name = "actually_checked_typescript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
swc_common = "0.31.10"
swc_ecma_ast = "0.104.3"
swc_ecma_parser = {version ="0.134.5", features= ["typescript"]}

[lib]
name = "act_lib"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[profile.release]
# lto = true
# strip = true
# opt-level = 3
